name: Code checks

on: [push]

jobs:
  build:
    runs-on: macos-latest
    name: Cheks
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        pip install pylint
        pip install pytest
        pip install pytest-cov
    - name: Black and Pylint
      run: black --diff --check $(git ls-files '*.py')
      run: pylint --disable=all --enable=unused-import $(git ls-files '*.py')

    - name: Pytest
      run: |
        pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
